name: Refresh Feed
on:
  schedule:
    - cron: 48 */4 * * *
permissions:
  contents: write
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Fetch API Data
        uses: SmartChain-AI/fetch-api-data-action@v2.4.0
        with:
          endpoint: https://market-api.ufcstrike.com/sets/376/circulation
          configuration: '{ "method": "GET" }'

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main # Pushes the updates to the main branch.
          folder: fetch-api-data-action # The location of the data.json file saved by the Fetch API Data action.
          target-folder: data # Saves the data into the 'data' directory
