name: Refresh Feed
on:
  schedule:
    - cron: 30 */1 * * *
permissions:
  contents: write
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://web-api.cryptoslam.io/v1/sales/ufcnft/summary?groupingtype=daily
          configuration: '{ "method": "GET" }'
          save-location: data
          save-name: test
          set-output: false
